### ISSUE TITLE
Práctica_Conexión De Bases de Datos

### ISSUE THREAD

**Issue by Eva155** [SistemasTecTlaxiaco/conexion-de-bases-de-datos-super_team#1]
[PRÁCTICA_CONEXIÓN DE BASE DE DATOS.pdf](https://github.com/SistemasTecTlaxiaco/conexion-de-bases-de-datos-super_team/files/6757229/PRACTICA_CONEXION.DE.BASE.DE.DATOS.pdf)

**Comment by javiern-778** [comment]
excelente trabajo cumplen con todos los requisitos: 20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado
